<?php
include('../template.php');
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	<meta name="description" content="UMR die Reinigungstechnik - die beste Wahl f�r professionelle Reinigung, Service, Schnelligkeit, Sauberkeit, Reinigung ihrer Objekte">
	<meta name="keywords" content="Reinigung, Objektreinigeung, Unterhaltsreinigung, Hauswartungen, Umzugsreinigung, Baureinigung, Fensterreinigung, Fassadenreinigung, B�roreinigung, Teppichreinigung, Sonderreinigung">
	<meta name="robots" content="index, follow" />
	<link rel="shortcut icon" href="http://umr.at/_images/logo/umr-icon-nn.ico">
	<title>UMR - Haftungsausschluss</title>
	<link href="<?php echo SITE_URL ?>/_css/default.css" rel="stylesheet" type="text/css">
</head>

<body>
	<br />
	<p style="font-size: 10px; text-align:justify; font-weight:normal; padding: 50px;">
		<strong>Haftungsausschluss </strong><br /><br />
		<b>1. Inhalt des Onlineangebotes</b><br /> Der Autor �bernimmt keinerlei Gew�hr f�r die Aktualit�t, Korrektheit, Vollst�ndigkeit oder Qualit�t der bereitgestellten Informationen. Haftungsanspr�che gegen den Autor, welche sich auf Sch�den materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollst�ndiger Informationen verursacht wurden, sind grunds�tzlich ausgeschlossen, sofern seitens des Autors kein nachweislich vors�tzliches oder grob fahrl�ssiges Verschulden vorliegt. Alle Angebote sind freibleibend und unverbindlich. Der Autor beh�lt es sich ausdr�cklich vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ank�ndigung zu ver�ndern, zu erg�nzen, zu l�schen oder die Ver�ffentlichung zeitweise oder endg�ltig einzustellen.
		<br /><b>2. Verweise und Links </b><br />Bei direkten oder indirekten Verweisen auf fremde Webseiten ("Hyperlinks"), die au�erhalb des Verantwortungsbereiches des Autors liegen, w�rde eine Haftungsverpflichtung ausschlie�lich in dem Fall in Kraft treten, in dem der Autor von den Inhalten Kenntnis hat und es ihm technisch m�glich und zumutbar w�re, die Nutzung im Falle rechtswidriger Inhalte zu verhindern. Der Autor erkl�rt hiermit ausdr�cklich, dass zum Zeitpunkt der Linksetzung keine illegalen Inhalte auf den zu verlinkenden Seiten erkennbar waren. Auf die aktuelle und zuk�nftige Gestaltung, die Inhalte oder die Urheberschaft der verlinkten/verkn�pften Seiten hat der Autor keinerlei Einfluss. Deshalb distanziert er sich hiermit ausdr�cklich von allen Inhalten aller verlinkten /verkn�pften Seiten, die nach der Linksetzung ver�ndert wurden. Diese Feststellung gilt f�r alle innerhalb des eigenen Internetangebotes gesetzten Links und Verweise sowie f�r Fremdeintr�ge in vom Autor eingerichteten G�steb�chern, Diskussionsforen, Linkverzeichnissen, Mailinglisten und in allen anderen Formen von Datenbanken, auf deren Inhalt externe Schreibzugriffe m�glich sind. F�r illegale, fehlerhafte oder unvollst�ndige Inhalte und insbesondere f�r Sch�den, die aus der Nutzung oder Nichtnutzung solcherart dargebotener Informationen entstehen, haftet allein der Anbieter der Seite, auf welche verwiesen wurde, nicht derjenige, der �ber Links auf die jeweilige Ver�ffentlichung lediglich verweist.
		<br /><b>3. Urheber- und Kennzeichenrecht </b><br />Der Autor ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Bilder, Grafiken, Tondokumente, Videosequenzen und Texte zu beachten, von ihm selbst erstellte Bilder, Grafiken, Tondokumente, Videosequenzen und Texte zu nutzen oder auf lizenzfreie Grafiken, Tondokumente, Videosequenzen und Texte zur�ckzugreifen. Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte gesch�tzten Marken- und Warenzeichen unterliegen uneingeschr�nkt den Bestimmungen des jeweils g�ltigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigent�mer. Allein aufgrund der blo�en Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte Dritter gesch�tzt sind! Das Copyright f�r ver�ffentlichte, vom Autor selbst erstellte Objekte bleibt allein beim Autor der Seiten. Eine Vervielf�ltigung oder Verwendung solcher Grafiken, Tondokumente, Videosequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdr�ckliche Zustimmung des Autors nicht gestattet.
		<br /><b>4. Datenschutz </b><br />Sofern innerhalb des Internetangebotes die M�glichkeit zur Eingabe pers�nlicher oder gesch�ftlicher Daten (Emailadressen, Namen, Anschriften) besteht, so erfolgt die Preisgabe dieser Daten seitens des Nutzers auf ausdr�cklich freiwilliger Basis. Die Inanspruchnahme und Bezahlung aller angebotenen Dienste ist - soweit technisch m�glich und zumutbar - auch ohne Angabe solcher Daten bzw. unter Angabe anonymisierter Daten oder eines Pseudonyms gestattet. Die Nutzung der im Rahmen des Impressums oder vergleichbarer Angaben ver�ffentlichten Kontaktdaten wie Postanschriften, Telefon- und Faxnummern sowie Emailadressen durch Dritte zur �bersendung von nicht ausdr�cklich angeforderten Informationen ist nicht gestattet. Rechtliche Schritte gegen die Versender von sogenannten Spam-Mails bei Verst�ssen gegen dieses Verbot sind ausdr�cklich vorbehalten.
		<br /><b>5. Rechtswirksamkeit dieses Haftungsausschlusses </b><br />Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diese Seite verwiesen wurde. Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollst�ndig entsprechen sollten, bleiben die �brigen Teile des Dokumentes in ihrem Inhalt und ihrer G�ltigkeit davon unber�hrt.
	</p>

	<p style="font-size: 10px; font-weight:normal; text-align:justify; padding: 50px;">
		<strong>Disclaimer </strong><br /><br />
		<b>1. Content</b><br /> The author reserves the right not to be responsible for the topicality, correctness, completeness or quality of the information provided. Liability claims regarding damage caused by the use of any information provided, including any kind of information which is incomplete or incorrect,will therefore be rejected. All offers are not-binding and without obligation. Parts of the pages or the complete publication including all offers and information might be extended, changed or partly or completely deleted by the author without separate announcement.
		<br /><b>2. Referrals and links </b><br />The author is not responsible for any contents linked or referred to from his pages - unless he has full knowledge of illegal contents and would be able to prevent the visitors of his site fromviewing those pages. If any damage occurs by the use of information presented there, only the author of the respective pages might be liable, not the one who has linked to these pages. Furthermore the author is not liable for any postings or messages published by users of discussion boards, guestbooks or mailinglists provided on his page.
		<br /><b>3. Copyright </b><br />The author intended not to use any copyrighted material for the publication or, if not possible, to indicate the copyright of the respective object. The copyright for any material created by the author is reserved. Any duplication or use of objects such as images, diagrams, sounds or texts in other electronic or printed publications is not permitted without the author's agreement.
		<br /><b>4. Privacy policy </b><br />If the opportunity for the input of personal or business data (email addresses, name, addresses) is given, the input of these data takes place voluntarily. The use and payment of all offered services are permitted - if and so far technically possible and reasonable - without specification of any personal data or under specification of anonymized data or an alias. The use of published postal addresses, telephone or fax numbers and email addresses for marketing purposes is prohibited, offenders sending unwanted spam messages will be punished.
		<br /><b>5. Legal validity of this disclaimer </b><br />This disclaimer is to be regarded as part of the internet publication which you were referred from. If sections or individual terms of this statement are not legal or correct, the content or validity of the other parts remain uninfluenced by this fact.
	</p>

</body>

</html>